cd ..
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.01 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adam --batch_size 64 --exps_dir 'exps/SimCLR_grid_search/adam_0.01_64/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.01 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adadelta --batch_size 64 --exps_dir 'exps/SimCLR_grid_search/adadelta_0.01_64/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.01 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adam --batch_size 128 --exps_dir 'exps/SimCLR_grid_search/adam_0.01_128/' &
CUDA_VISIBLE_DEVICES=3 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.01 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adadelta --batch_size 128 --exps_dir 'exps/SimCLR_grid_search/adadelta_0.01_128/' &
CUDA_VISIBLE_DEVICES=4 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.01 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adam --batch_size 256 --exps_dir 'exps/SimCLR_grid_search/adam_0.01_256/' &
CUDA_VISIBLE_DEVICES=5 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.01 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adadelta --batch_size 256 --exps_dir 'exps/SimCLR_grid_search/adadelta_0.01_256/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.001 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adam --batch_size 64 --exps_dir 'exps/SimCLR_grid_search/adam_0.001_64/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.001 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adadelta --batch_size 64 --exps_dir 'exps/SimCLR_grid_search/adadelta_0.001_64/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.001 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adam --batch_size 128 --exps_dir 'exps/SimCLR_grid_search/adam_0.001_128/' &
CUDA_VISIBLE_DEVICES=3 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.001 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adadelta --batch_size 128 --exps_dir 'exps/SimCLR_grid_search/adadelta_0.001_128/' &
CUDA_VISIBLE_DEVICES=4 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.001 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adam --batch_size 256 --exps_dir 'exps/SimCLR_grid_search/adam_0.001_256/' &
CUDA_VISIBLE_DEVICES=5 python TrainingAnomalyDetector_SimCLR.py  --features_path_1 'features1' --features_path_2 'features2' --objective_name 'SimCLRLoss' --network_name 'TripletAnomalyDetector' --annotation_path 'Train_Annotation.txt' --lr_base 0.001 --epochs 5 --dropout_rate 0.5 --lambdas 8e-05 --optimizer adadelta --batch_size 256 --exps_dir 'exps/SimCLR_grid_search/adadelta_0.001_256/'
wait